#11 CRUD operations for buses
atlp-rwanda/rca-phantom-team2-bn pull request #17
Opened 2023-04-03 13:41 UTC by degide

#### What does this PR do?

Add CRUD operations for buses

#### Description of Task to be completed?

The task involves creating all CRUD operations endpoints for a bus. These endpoints are exposed after the PR:

`PUT /buses`

`GET /buses`

`GET /buses/bus/{busId}`

`PUT /buses/{busId}`

`DELETE /buses/{busId}`

#### How should this be manually tested?

After cloning and checking out this branch, follow these steps:

1. Set up the project including database (using environment variables)
2. Open your browser and visit: [http://localhost:4000/api-docs](http://localhost:4000/api-docs)
3. Test the endpoints listed above using the swagger documentation
4. 
5. #### What are the relevant pivotal tracker/Trello stories?

Trello story: [#11](https://trello.com/c/N4hEovZJ/11-crud-operations-for-buses)

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/50821898/229527176-021241bb-5885-486e-81fa-a4621483004c.png)

2023-04-04 09:56 UTC, kelliaUmuhire reviewed
Nice work @degide. Would you resolve the conflicts?

2023-04-05 09:15 UTC, dmutoni requested changes, later dismissed

2023-04-05 09:15 UTC, dmutoni commented on src/controllers/buses.controller.ts
> +    const bus = await (await Bus.create(req.body)).save()
Can we specify the type of bus here? like the data type of that variable bus

2023-04-05 09:15 UTC, dmutoni commented on src/controllers/buses.controller.ts
> +        where: {id: req.params.busId}
Also here, since we are using typescript can we specify the type of UpdateCount

2023-04-05 09:15 UTC, dmutoni commented on src/controllers/buses.controller.ts
> +    const bus = await Bus.findByPk(req.params.busId)
Also here, specify the type of bus

2023-04-05 09:15 UTC, dmutoni commented on src/routes/buses.router.ts
> +import { createBus, deleteBusById, getAllBuses, getBusById, updateBusById } from "../controllers/buses.controller"
Can we please have a comma at the end of updateBusById so that the code may look cleaner?

2023-04-05 09:15 UTC, dmutoni commented on src/validations/buses.ts
> +import { Request, NextFunction, Response } from "express"
Can we have the trailing comma here after Response?

2023-04-05 09:17 UTC, dmutoni commented
Overall, you've done a great job 🎊, but I would like you to specify the types of variables

2023-04-05 09:31 UTC, degide commented on src/validations/buses.ts
> +import { Request, NextFunction, Response } from "express"
for these variables like `bus` the types are already inferred from the expression. anyway, I'm adding them

2023-04-05 12:15 UTC, kelliaUmuhire approved these changes
Nice work @degide!

2023-04-05 13:48 UTC, MikeManzi approved these changes

2023-04-05 14:55 UTC, freddykaberuka approved these changes

2023-04-05 15:14 UTC, merged